### ISSUE TITLE
about file error

### ISSUE THREAD

**Issue by DuTim** [RossiXu/event-centric-opinion-mining#1]
dear RossiXu:
        Thank you for your very good research ! 
         I try to reproduct the code ,But I find some question about the code.
        First ,the about data link is error. It don't link right place ,I think there is a case error in this link.
        Second, There seems to be an error in the data reading part of your code(reader.py), your code should be prepared to handle TXT format, json format file cannot load data correctly. Or do I have a problem?
![image](https://user-images.githubusercontent.com/50939742/163083121-96b882e2-9a65-4f32-ae11-42ae65708fa1.png)
![image](https://user-images.githubusercontent.com/50939742/161383529-7c5bcfe9-e302-498f-bdfd-2d3681f0592d.png)

**Comment by wangyujie1176** [comment]
hello, the ECO_Bank.zip contains "train.json,test.json and dev.json" 3 files from http://www.e-com.ac.cn/,  it not contain "trian.txt,test.txt,dev.txt" . where I can download  these 3 files.

**Comment by DuTim** [comment]
> hello, the ECO_Bank.zip contains "train.json,test.json and dev.json" 3 files from http://www.e-com.ac.cn/, it not contain "trian.txt,test.txt,dev.txt" . where I can download these 3 files.

这几个文件是根据作者之前的代码手动调整生成的,这几个文件是没有被使用的,我会对图片进行替换,防止大家被误导.

**Comment by RossiXu** [comment]
Thank you very much for your question.
The data link and code has been fixed.
You can try again.
