### ISSUE TITLE
num_samples=0 error

### ISSUE THREAD

**Issue by yeoserene** [RossiXu/event-centric-opinion-mining#2]
Hi, upon running this command 

python ote_model/mrc/main.py \
      --model_name_or_path luhua/chinese_pretrain_mrc_roberta_wwm_ext_large \
      --do_train \
      --do_eval \
      --do_lower_case \
      --learning_rate 3e-5 \
      --num_train_epochs 5 \
      --per_gpu_eval_batch_size=4 \
      --per_gpu_train_batch_size=6 \
      --evaluate_during_training \
      --output_dir model_files/chinese_model/mrc/ \
      --data_dir data/ECOB-ZH/ \
      --result_dir result/chinese_result/

I encountered the following error: 

Traceback (most recent call last):
  File "ote_model/mrc/main.py", line 504, in <module>
    main()
  File "ote_model/mrc/main.py", line 446, in main
    global_step, tr_loss = train(args, train_dataset, model, tokenizer)
  File "ote_model/mrc/main.py", line 52, in train
    train_sampler = RandomSampler(train_dataset) if args.local_rank == -1 else DistributedSampler(train_dataset)
  File "/home/user/anaconda3/envs/ecom/lib/python3.8/site-packages/torch/utils/data/sampler.py", line 103, in __init__
    raise ValueError("num_samples should be a positive integer "
ValueError: num_samples should be a positive integer value, but got num_samples=0

Is there something wrong? I ran the same code but with ECOB-EN but the code works fine.

**Comment by RossiXu** [comment]
Thank you for your question.
I also tried running this command, but didn't encounter similar error whether with ECOB_EN or with ECOB_ZH.
Maybe you can use the latest version of the code and data and try again.
If any other questions, you can contact me by email.
