### ISSUE TITLE
fields in annotated data

### ISSUE THREAD

**Issue by yeoserene** [RossiXu/event-centric-opinion-mining#3]
Hi,

Can I understand the fields in the annotated data? In particular, 

            [
                "Apple could be ordered to pay billions of euros in back taxes in the Republic of Ireland by European Union competition officials.",
                "O",
                "O"
            ],

What does the "O" and "O" mean? Thanks!

**Comment by RossiXu** [comment]
Thank you for your attention to this work.
In each annotated sentence, first element in the list is raw text of the sentence, second element is BIO tag to label opinion segments and third element is corresponding event argument (opinion target) of the opinion segment. We assign the third element "O" when the sentence is not part of an opinion segment.
So the "O" and "O" mean the sentence is not an opinion sentence and naturally has no opinion target.
You can find more detailed introduction for data format in README.md from [ECO_Bank.zip](http://123.57.148.143/ECO_Bank.zip).
